name: please
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-266.7.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flushbar: ^1.10.4
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.18.3
  flutter_slidable: ^1.3.0
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  json_annotation: ^4.5.0
  kt_dart: ^0.10.0
  go_router: ^3.1.1
  equatable: ^2.0.3
  http: ^0.13.4
  google_fonts: ^3.0.1
  shared_preferences: ^2.0.15
  test: ^1.21.1
  mockito: ^5.2.0
  sqflite: ^2.0.2+1
  sqlbrite: ^2.2.0
  build_runner: ^2.1.11
  path_provider: ^2.0.10
  synchronized: ^3.0.0+2
  data_connection_checker: ^0.3.4
  bloc_test: ^9.0.3
  connectivity: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  injectable_generator: ^1.5.3
  lint: ^1.8.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/


